services:
  mongodb:
    image: mongo:8.0-noble
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - osm-network
    restart: always

  user-service:
    image: osm-user-service:latest
    ports:
      - "4001:4001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/userservice
    depends_on:
      - mongo
    networks:
      - osm-network
    restart: always

  product-service:
    image: osm-product-service:latest
    container_name: product-service
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/productservice
    depends_on:
      - mongo
    networks:
      - osm-network
    restart: always

  order-service:
    image: osm-order-service:latest
    container_name: order-service
    ports:
      - "4003:4003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/orderservice
    depends_on:
      - mongo
    networks:
      - osm-network
    restart: always

  payment-service:
    image: osm-payment-service:latest
    container_name: payment-service
    ports:
      - "4004:4004"
    networks:
      - osm-network
    restart: always

  frontend:
    image: osm-frontend:latest
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
    networks:
      - osm-network
    restart: always

networks:
  osm-network:
    driver: bridge

volumes:
  mongo-data:
