apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: osm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:8.0-noble
          ports:
            - containerPort: 27017         

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: osm
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017