apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: osm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: nguyenducmanh247/osm-order-service:latest
          ports:
            - containerPort: 4003
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/orderservice          

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: osm
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003