apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: osm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: nguyenducmanh247/osm-order-service:latest
          ports:
            - containerPort: 4003
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/orderservice
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi            

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: osm
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003