apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: osm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: nguyenducmanh247/osm-product-service:latest
          ports:
            - containerPort: 4002
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/productservice

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: osm
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002